mainer

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,6 +1,10 @@
 on:
-  push:
-  pull_request:
+  workflow_dispatch:
+    inputs:
+      working-directory:
+        description: 'The working directory to run the workflow in'
+        required: true
+        type: string
 permissions:
     actions: none
     attestations: none
@@ -17,85 +21,10 @@ permissions:
     repository-projects: none
     security-events: none
     statuses: none
-
-env:
-    SRC_DIR: ./src
     
 jobs:
-  penultimate:
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-    outputs:
-      python-packages: ${{ steps.find-python-packages.outputs.packages}}
-      node-packages: ${{ steps.find-node-packages.outputs.packages }}
-      container-projects: ${{ steps.find-container-projects.outputs.images }}
-      all-modified-directories: ${{ steps.modified-directories.outputs.all_modified_files }}
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          lfs: true
-          fetch-depth: 2
-          submodules: true
-          persist-credentials: false
-      - name: List files
-        id: list-files
-        run: |
-          echo "::group::Files"
-          find . -type f -print0 | xargs -0 ls -l
-          echo "::endgroup::"
-      - name: Find Python packages
-        id: find-python-packages
-        if: hashFiles(format('{0}/**/pyproject.toml', env.SRC_DIR))
-        working-directory: ${{ env.SRC_DIR }}
-        run: |
-          PACKAGES=$(find . -name pyproject.toml -exec dirname {} \; | sed 's/^\.\///' | jq -R -s -c 'split("\n")[:-1]')
-          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
-      - name: Find Node packages
-        id: find-node-packages
-        if: hashFiles(format('{0}/**/package.json', env.SRC_DIR))
-        working-directory: ${{ env.SRC_DIR }}
-        run: |
-          PACKAGES=$(find . -name package.json -exec dirname {} \; | sed 's/^\.\///' | jq -R -s -c 'split("\n")[:-1]')
-          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT      
-      - name: Find Container Projects
-        id: find-container-projects
-        if: hashFiles(format('{0}/**/Dockerfile', env.SRC_DIR))
-        working-directory: ${{ env.SRC_DIR }}
-        run: |
-          IMAGES=$(find . -name Dockerfile -exec dirname {} \; | sed 's/^\.\///' | jq -R -s -c 'split("\n")[:-1]')
-          echo "images=$IMAGES" >> $GITHUB_OUTPUT      
-      - name: Find Modified Directories
-        id: modified-directories
-        if: hashFiles(format('{0}', env.SRC_DIR))
-        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
-        with:
-          path: ${{ env.SRC_DIR }}
-          dir_names: true
-          dir_names_max_depth: 1
-          json: true
-          escape_json: true
-          matrix: true
-      - name: Debug
-        id: debug
-        run: |
-          echo "Debugging Outputs"
-          echo "::group::Python Packages"
-          echo "${{ steps.find-python-packages.outputs.packages }}"
-          echo "::endgroup::"
-          echo "::group::Node Packages"
-          echo "${{ steps.find-node-packages.outputs.packages }}"
-          echo "::endgroup::"
-          echo "::group::Container Projects"
-          echo "${{ steps.find-container-projects.outputs.images }}"
-          echo "::endgroup::"
-          echo "::group::Modified Directories"
-          echo "${{ steps.modified-directories.outputs.all_modified_files }}"
-          echo "::endgroup::"
-
-  omega:
-    needs: [penultimate]
-    if: ${{ needs.penultimate.outputs.all-modified-directories != '[]' && needs.penultimate.outputs.all-modified-directories != '' }}
+  build:
+    name: build ${{ inputs.working-directory }} (${{ matrix.platform }})
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -105,35 +34,89 @@ jobs:
           lfs: true
           submodules: true
           persist-credentials: false
-      - name: Docker
-        id: exists-dockerfile
-        if: hashFiles(format('{0}/{1}/Dockerfile', env.SRC_DIR, matrix.all-modified-directories))
+      # - name: Check for a Dockerfile
+      #   if: ! ${{ hashFiles(format('{0}/Dockerfile', inputs.working-directory)) }}
+      #   run: |
+      #     echo "::warning::No Dockerfile found in ${{ inputs.working-directory }}. Failing build."
+      #     exit 1
+      - name: Prepare
         run: |
-          echo "::group::Dockerfile"
-          cat "${{ format('{0}/{1}/Dockerfile', env.SRC_DIR, matrix.all-modified-directories) }}"
-          echo "::endgroup::"
-          gh api \
-            --method POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            -f ref=${{ github.ref }} \
-            -f inputs[working-directory]=${{ format('{0}/{1}', env.SRC_DIR, matrix.all-modified-directories) }}
-            /repos/${{ github.repository }}/actions/workflows/docker.yml/dispatches
-      - name: Python
-        id: exists-python
-        if: hashFiles(format('{0}/{1}/pyproject.toml', env.SRC_DIR, matrix.all-modified-directories))
+          platform=${{ matrix.platform }}
+          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
+      - name: Docker meta
+        id: meta
+        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
+        with:
+          images: ${{ inputs.working-directory }}
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
+        with:
+          buildkitd-flags: --debug
+      - name: Build and push by digest
+        id: build
+        if: hashFiles(format('{0}/Dockerfile', inputs.working-directory))
+        uses: docker/build-push-action@v6
+        with:
+          platforms: ${{ matrix.platform }}
+          labels: ${{ steps.meta.outputs.labels }}
+          tags: ${{ inputs.working-directory }}
+          push: false
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          context: ${{ inputs.working-directory }}
+          file: ${{ inputs.working-directory }}/Dockerfile
+          outputs: type=image,push-by-digest=true,name-canonical=true
+      - name: Export digest
         run: |
-          echo "::group::pyproject.toml"
-          cat "${{ format('{0}/{1}/pyproject.toml', env.SRC_DIR, matrix.all-modified-directories) }}"
-          echo "::endgroup::"
-      - name: Node
-        id: exists-node
-        if: hashFiles(format('{0}/{1}/package.json', env.SRC_DIR, matrix.all-modified-directories))
-        run: |
-          echo "::group::package.json"
-          cat "${{ format('{0}/{1}/package.json', env.SRC_DIR, matrix.all-modified-directories) }}"
-          echo "::endgroup::"
+          mkdir -p ${{ runner.temp }}/digests
+          digest="${{ steps.build.outputs.digest }}"
+          touch "${{ runner.temp }}/digests/${digest#sha256:}"
+      - name: Upload digest
+        uses: actions/upload-artifact@v4
+        with:
+          name: digests-${{ env.PLATFORM_PAIR }}
+          path: ${{ runner.temp }}/digests/*
+          if-no-files-found: error
+          retention-days: 1
     strategy:
       fail-fast: false
       matrix:
-        all-modified-directories: ${{ fromJson(needs.penultimate.outputs.all-modified-directories) }}
+        platform: [ 'linux/amd64', 'linux/arm64' ]
+
+
+#   merge:
+#     runs-on: ubuntu-latest
+#     needs:
+#       - build
+#     steps:
+#       - name: Download digests
+#         uses: actions/download-artifact@v4
+#         with:
+#           path: ${{ runner.temp }}/digests
+#           pattern: digests-*
+#           merge-multiple: true
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v3
+#       - name: Docker meta
+#         id: meta
+#         uses: docker/metadata-action@v5
+#         with:
+#           images: ${{ inputs.working-directory }}
+#           tags: |
+#             type=ref,event=branch
+#             type=ref,event=pr
+#             type=semver,pattern={{version}}
+#             type=semver,pattern={{major}}.{{minor}}
+
+#       - name: Create manifest list and push
+#         working-directory: ${{ runner.temp }}/digests
+#         run: |
+#           docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
+#             $(printf '${{ inputs.working-directory }}@sha256:%s ' *)
+#       - name: Inspect image
+#         run: |
+#           docker buildx imagetools inspect ${{ inputs.working-directory }}:${{ steps.meta.outputs.version }}
